version: '3'

services:
  portainer:
    image: portainerci/portainer:pr6644
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - 9000:9000
      - 9443:9443
    
volumes:
  portainer_data: